[package]
name = "webrender-bindings-gtest"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
vulkan = ["dep:webrender", "dep:ash", "dep:wgpu_bindings", "dep:wgc", "dep:wgt", "webrender/vulkan"]

[dependencies]
webrender = { path = "../../wr/webrender", default-features = false, optional = true }
ash = { version = "0.38", optional = true }
wgpu_bindings = { path = "../../wgpu_bindings", optional = true }
wgc = { package = "wgpu-core", git = "https://github.com/gfx-rs/wgpu", rev = "4f4dc63098fae64a0e6d1d3dc6f4f328da8fd5c8", optional = true }
wgt = { package = "wgpu-types", git = "https://github.com/gfx-rs/wgpu", rev = "4f4dc63098fae64a0e6d1d3dc6f4f328da8fd5c8", optional = true }

[lib]
path = "lib.rs"
test = false
doctest = false
