[source.firefox-wgpu]
git = "https://github.com/gfx-rs/wgpu"
rev = "4f4dc63098fae64a0e6d1d3dc6f4f328da8fd5c8"
replace-with = "firefox-vendored"

[source.firefox-vendored]
directory = "../../third_party/rust"
